name: foo_lint
description: Lint rules for my flutter project with multi rules for the different project types.
version: 1.0.0+3
repository: https://github.com/sonnts996/foo-lint

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter_lints: ^1.0.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
